/* EvaluationChart-Test.sas
Created: 		19-Mar-2016
Modified;		18-Jun-2017
Author: 		Daniel Mastropietro
Description: 	Tests run on macro %EvaluationChart
Dependencies:	%RunTestHarness macro
Notes:			The test code makes use of a test harness dataset defined in the same directory.
				This program compares the output datasets generated by the tested macro using PROC COMPARE.
				We should "manually" check that the output of PROC COMPARE indicates that the observed and
				expected output datasets are the same (at least in all variables except MODEL which contains
				the name of the name of the dataset used in the model being evaluated by %EvaluationChart
				(ex: this column contains _DATA.TOTEST_01 for the observed output and TOTEST_01 for the expected output)
*/


/*------------------------ Generate expected results ----------------------------*/
%let testmacro = EvaluationChart;
%let testpath = E:\Daniel\SAS\Macros\tests\&testmacro;
libname _data "&testpath\data";		%* This test data library name should coincide with the name used by the %RunTestHarness macro when mapping the DATADIR directory;

* All non-events;
data _data.totest_00a;
	input y p leaf;
datalines;
0 0.01 1
0 0.23 2
0 0.01 1
;
* All events;
data _data.totest_00b;
	input y p leaf;
datalines;
1 0.01 1
1 0.23 2
1 0.01 1
;

data _data.totest_01;
	input y p leaf;
datalines;
0 0.01 1
0 0.23 2
0 0.01 1
1 0.01 1
0 0.15 3
0 0.15 3
1 0.23 2
0 0.26 4
1 0.28 5
1 0.65 6
;

* Perfect ordering with just one event;
data _data.totest_02;
	input y p leaf;
datalines;
0 0.01 1
0 0.23 2
0 0.01 1
0 0.01 1
0 0.15 3
0 0.15 3
0 0.23 2
0 0.26 4
0 0.28 5
1 0.65 6
;

* Read the Test Harness dataset;
%import(TestHarness_&testmacro, "&testpath\TestHarness-&testmacro..csv");

* Generate the EXPECTED results and save them;
%RunTestHarness(
	&testmacro,
	TestHarness_&testmacro,
	library=_data,
	checkoutput=OUT OUTSTAT,
	saveoutput=1,
	resultsdir=&testpath\expected
);
/*------------------------ Generate expected results ----------------------------*/


/*----------------------------- Run Test Harness --------------------------------*/
* Setup;
%let testmacro = EvaluationChart;
%let testpath = E:\Daniel\SAS\Macros\tests\&testmacro;
libname test "&testpath";

* Read the Test Harness dataset;
%import(TestHarness_&testmacro, "&testpath\TestHarness-&testmacro..csv");

%RunTestHarness(
	&testmacro,
	TestHarness_&testmacro,
	checkoutput=OUT OUTSTAT,
	datadir=&testpath\data,
	resultsdir=&testpath\expected
);
/*----------------------------- Run Test Harness --------------------------------*/
