* Code to compile macros into SASMSTORE catalog located in /free/SAS/SAS_9.1/sasmacros on UNIX server;
* Created: 11JUN06;
rsubmit;
libname macros '/free/SAS/SAS_9.1/sasmacros';
options mstored sasmstore=macros;
endrsubmit;
* Define macro variables used in each macro code;
%let rsubmit = rsubmit;
* Compile macros;
%include 'C:\SAS\Macros\Compile\All.sas'; endrsubmit;                          * 1;
%include 'C:\SAS\Macros\Compile\Any.sas'; endrsubmit;                          * 2;
%include 'C:\SAS\Macros\Compile\Boxcox.sas'; endrsubmit;                       * 3;
%include 'C:\SAS\Macros\Compile\CallMacro.sas'; endrsubmit;                    * 4;
%include 'C:\SAS\Macros\Compile\Categorize.sas'; endrsubmit;                   * 5;
%include 'C:\SAS\Macros\Compile\Center.sas'; endrsubmit;                       * 6;
%include 'C:\SAS\Macros\Compile\CheckDiff.sas'; endrsubmit;                    * 7;
%include 'C:\SAS\Macros\Compile\CheckInputParameters.sas'; endrsubmit;         * 8;
%include 'C:\SAS\Macros\Compile\CheckRepeated.sas'; endrsubmit;                * 9;
%include 'C:\SAS\Macros\Compile\CheckRequiredParameters.sas'; endrsubmit;      * 10;
%include 'C:\SAS\Macros\Compile\Chisq.sas'; endrsubmit;                        * 11;
%include 'C:\SAS\Macros\Compile\Colors.sas'; endrsubmit;                       * 12;
%include 'C:\SAS\Macros\Compile\CompareLists.sas'; endrsubmit;                 * 13;
%include 'C:\SAS\Macros\Compile\Compute.sas'; endrsubmit;                      * 14;
%include 'C:\SAS\Macros\Compile\Cov.sas'; endrsubmit;                          * 15;
%include 'C:\SAS\Macros\Compile\CreateDummyVar.sas'; endrsubmit;               * 16;
%include 'C:\SAS\Macros\Compile\CreateGroupVar.sas'; endrsubmit;               * 17;
%include 'C:\SAS\Macros\Compile\CreateInteractions.sas'; endrsubmit;           * 18;
%include 'C:\SAS\Macros\Compile\CreateLags.sas'; endrsubmit;                   * 19;
%include 'C:\SAS\Macros\Compile\CreatePrevPostVar.sas'; endrsubmit;            * 20;
%include 'C:\SAS\Macros\Compile\CreateVarFromList.sas'; endrsubmit;            * 21;
%include 'C:\SAS\Macros\Compile\CreateVarList.sas'; endrsubmit;                * 22;
%include 'C:\SAS\Macros\Compile\CutMahalanobisChi.sas'; endrsubmit;            * 23;
%include 'C:\SAS\Macros\Compile\DefineSymbols.sas'; endrsubmit;                * 24;
%include 'C:\SAS\Macros\Compile\Delet.sas'; endrsubmit;                        * 25;
%include 'C:\SAS\Macros\Compile\DeleteMacroVar.sas'; endrsubmit;               * 26;
%include 'C:\SAS\Macros\Compile\Det.sas'; endrsubmit;                          * 27;
%include 'C:\SAS\Macros\Compile\DetectCollinearities.sas'; endrsubmit;         * 28;
%include 'C:\SAS\Macros\Compile\DetectOutliers.sas'; endrsubmit;               * 29;
%include 'C:\SAS\Macros\Compile\DetectOutliersHadi.sas'; endrsubmit;           * 30;
%include 'C:\SAS\Macros\Compile\DetectOutliersMAD.sas'; endrsubmit;            * 31;
%include 'C:\SAS\Macros\Compile\Dfbetas.sas'; endrsubmit;                      * 32;
%include 'C:\SAS\Macros\Compile\Drop.sas'; endrsubmit;                         * 33;
%include 'C:\SAS\Macros\Compile\EvalExp.sas'; endrsubmit;                      * 34;
%include 'C:\SAS\Macros\Compile\EvaluationChart.sas'; endrsubmit;              * 35;
%include 'C:\SAS\Macros\Compile\Exist.sas'; endrsubmit;                        * 36;
%include 'C:\SAS\Macros\Compile\ExistData.sas'; endrsubmit;                    * 37;
%include 'C:\SAS\Macros\Compile\ExistMacroVar.sas'; endrsubmit;                * 38;
%include 'C:\SAS\Macros\Compile\ExistOption.sas'; endrsubmit;                  * 39;
%include 'C:\SAS\Macros\Compile\ExistVar.sas'; endrsubmit;                     * 40;
%include 'C:\SAS\Macros\Compile\Export.sas'; endrsubmit;                       * 41;
%include 'C:\SAS\Macros\Compile\FindInList.sas'; endrsubmit;                   * 42;
%include 'C:\SAS\Macros\Compile\FindMatch.sas'; endrsubmit;                    * 43;
%include 'C:\SAS\Macros\Compile\FittedPlots.sas'; endrsubmit;                  * 44;
%include 'C:\SAS\Macros\Compile\FixBreak.sas'; endrsubmit;                     * 45;
%include 'C:\SAS\Macros\Compile\FixNames.sas'; endrsubmit;                     * 46;
%include 'C:\SAS\Macros\Compile\Freq.sas'; endrsubmit;                         * 47;
%include 'C:\SAS\Macros\Compile\FreqMult.sas'; endrsubmit;                     * 48;
%include 'C:\SAS\Macros\Compile\GainsChart.sas'; endrsubmit;                   * 49;
%include 'C:\SAS\Macros\Compile\GetDataName.sas'; endrsubmit;                  * 50;
%include 'C:\SAS\Macros\Compile\GetDataOptions.sas'; endrsubmit;               * 51;
%include 'C:\SAS\Macros\Compile\GetLibraryName.sas'; endrsubmit;               * 52;
%include 'C:\SAS\Macros\Compile\Getnobs.sas'; endrsubmit;                      * 53;
%include 'C:\SAS\Macros\Compile\GetNroElements.sas'; endrsubmit;               * 54;
%include 'C:\SAS\Macros\Compile\GetRegVarList.sas'; endrsubmit;                * 55;
%include 'C:\SAS\Macros\Compile\GetStat.sas'; endrsubmit;                      * 56;
%include 'C:\SAS\Macros\Compile\GetVarList.sas'; endrsubmit;                   * 57;
%include 'C:\SAS\Macros\Compile\GetVarNames.sas'; endrsubmit;                  * 58;
%include 'C:\SAS\Macros\Compile\GetVarOrder.sas'; endrsubmit;                  * 59;
%include 'C:\SAS\Macros\Compile\GetVarType.sas'; endrsubmit;                   * 60;
%include 'C:\SAS\Macros\Compile\Gini.sas'; endrsubmit;                         * 61;
%include 'C:\SAS\Macros\Compile\GraphStrata.sas'; endrsubmit;                  * 62;
%include 'C:\SAS\Macros\Compile\GraphXY.sas'; endrsubmit;                      * 63;
%include 'C:\SAS\Macros\Compile\Hadi.sas'; endrsubmit;                         * 64;
%include 'C:\SAS\Macros\Compile\Help.sas'; endrsubmit;                         * 65;
%include 'C:\SAS\Macros\Compile\Import.sas'; endrsubmit;                       * 66;
%include 'C:\SAS\Macros\Compile\InformationValue.sas'; endrsubmit;             * 67;
%include 'C:\SAS\Macros\Compile\InsertInList.sas'; endrsubmit;                 * 68;
%include 'C:\SAS\Macros\Compile\IsNumber.sas'; endrsubmit;                     * 69;
%include 'C:\SAS\Macros\Compile\KeepInList.sas'; endrsubmit;                   * 70;
%include 'C:\SAS\Macros\Compile\KS.sas'; endrsubmit;                           * 71;
%include 'C:\SAS\Macros\Compile\LiftChart.sas'; endrsubmit;                    * 72;
%include 'C:\SAS\Macros\Compile\LogisticRegression.sas'; endrsubmit;           * 73;
%include 'C:\SAS\Macros\Compile\LogReg1.sas'; endrsubmit;                      * 74;
%include 'C:\SAS\Macros\Compile\Mahalanobis.sas'; endrsubmit;                  * 75;
%include 'C:\SAS\Macros\Compile\MakeList.sas'; endrsubmit;                     * 76;
%include 'C:\SAS\Macros\Compile\MakeListFromName.sas'; endrsubmit;             * 77;
%include 'C:\SAS\Macros\Compile\MakeListFromVar.sas'; endrsubmit;              * 78;
%include 'C:\SAS\Macros\Compile\MakeVar.sas'; endrsubmit;                      * 79;
%include 'C:\SAS\Macros\Compile\Means.sas'; endrsubmit;                        * 80;
%include 'C:\SAS\Macros\Compile\Merge.sas'; endrsubmit;                        * 81;
%include 'C:\SAS\Macros\Compile\MissingValues.sas'; endrsubmit;                * 82;
%include 'C:\SAS\Macros\Compile\MPlot.sas'; endrsubmit;                        * 83;
%include 'C:\SAS\Macros\Compile\Oversampling.sas'; endrsubmit;                 * 84;
%include 'C:\SAS\Macros\Compile\PartialCorrelation.sas'; endrsubmit;           * 85;
%include 'C:\SAS\Macros\Compile\PartialPlots.sas'; endrsubmit;                 * 86;
%include 'C:\SAS\Macros\Compile\PiecewiseTransf.sas'; endrsubmit;              * 87;
%include 'C:\SAS\Macros\Compile\PiecewiseTransfCuts.sas'; endrsubmit;          * 88;
%include 'C:\SAS\Macros\Compile\Pretty.sas'; endrsubmit;                       * 89;
%include 'C:\SAS\Macros\Compile\PrintDataDoesNotExist.sas'; endrsubmit;        * 90;
%include 'C:\SAS\Macros\Compile\PrintNameList.sas'; endrsubmit;                * 91;
%include 'C:\SAS\Macros\Compile\PrintRequiredParameterMissing.sas'; endrsubmit;* 92;
%include 'C:\SAS\Macros\Compile\PrintVarDoesNotExist.sas'; endrsubmit;         * 93;
%include 'C:\SAS\Macros\Compile\Puts.sas'; endrsubmit;                         * 94;
%include 'C:\SAS\Macros\Compile\Qqplot.sas'; endrsubmit;                       * 95;
%include 'C:\SAS\Macros\Compile\ReadMacroVar.sas'; endrsubmit;                 * 96;
%include 'C:\SAS\Macros\Compile\RemoveFromList.sas'; endrsubmit;               * 97;
%include 'C:\SAS\Macros\Compile\RemovePrefix.sas'; endrsubmit;                 * 98;
%include 'C:\SAS\Macros\Compile\RemoveRepeated.sas'; endrsubmit;               * 99;
%include 'C:\SAS\Macros\Compile\RemoveSuffix.sas'; endrsubmit;                 * 100;
%include 'C:\SAS\Macros\Compile\RenameVariables.sas'; endrsubmit;              * 101;
%include 'C:\SAS\Macros\Compile\Rep.sas'; endrsubmit;                          * 102;
%include 'C:\SAS\Macros\Compile\ReplaceChar.sas'; endrsubmit;                  * 103;
%include 'C:\SAS\Macros\Compile\ReplaceMissing.sas'; endrsubmit;               * 104;
%include 'C:\SAS\Macros\Compile\ResetSASOptions.sas'; endrsubmit;              * 105;
%include 'C:\SAS\Macros\Compile\Rsquare.sas'; endrsubmit;                      * 106;
%include 'C:\SAS\Macros\Compile\SaveMacroVar.sas'; endrsubmit;                 * 107;
%include 'C:\SAS\Macros\Compile\SaveResults.sas'; endrsubmit;                  * 108;
%include 'C:\SAS\Macros\Compile\Scatter.sas'; endrsubmit;                      * 109;
%include 'C:\SAS\Macros\Compile\ScoreCalibration.sas'; endrsubmit;             * 110;
%include 'C:\SAS\Macros\Compile\SelectName.sas'; endrsubmit;                   * 111;
%include 'C:\SAS\Macros\Compile\SelectNames.sas'; endrsubmit;                  * 112;
%include 'C:\SAS\Macros\Compile\SelectVar.sas'; endrsubmit;                    * 113;
%include 'C:\SAS\Macros\Compile\SetAxis.sas'; endrsubmit;                      * 114;
%include 'C:\SAS\Macros\Compile\SetSASOptions.sas'; endrsubmit;                * 115;
%include 'C:\SAS\Macros\Compile\SetVarOrder.sas'; endrsubmit;                  * 116;
%include 'C:\SAS\Macros\Compile\Sort.sas'; endrsubmit;                         * 117;
%include 'C:\SAS\Macros\Compile\Standardize.sas'; endrsubmit;                  * 118;
%include 'C:\SAS\Macros\Compile\Subset.sas'; endrsubmit;                       * 119;
%include 'C:\SAS\Macros\Compile\SymmetricAxis.sas'; endrsubmit;                * 120;
%include 'C:\SAS\Macros\Compile\TestLogisticFit.sas'; endrsubmit;              * 121;
%include 'C:\SAS\Macros\Compile\Transpose.sas'; endrsubmit;                    * 122;
%include 'C:\SAS\Macros\Compile\VariableImpact.sas'; endrsubmit;               * 123;
%include 'C:\SAS\Macros\Compile\VarOrder.sas'; endrsubmit;                     * 124;
* Unlock sasmacr catalog;
rsubmit;
options sasmstore=sashelp;
%macro dummy / store; %mend;
libname macros '/free/SAS/SAS_9.1/sasmacros' access=readonly;
options sasmstore=macros;
endrsubmit;
%let rsubmit =;
